[package]
name = "cm"
version = "0.1.0"
authors = ["rexim <reximkut@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.99.0"
libc = "0.2.69"
regex = "1"